version: '3.9'

services:
  db:
    image: postgres:13.0-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    env_file:
      - .env
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  images:
    build:
      context: .
      dockerfile: ./docker/images.Dockerfile
    container_name: images
    entrypoint: ./server-entrypoint.sh
    expose:
      - 8001
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - POSTGRES_SERVER=db
    volumes:
      - ./images:/app/images

  web:
    build:
      context: .
      dockerfile: ./docker/web.Dockerfile
    container_name: web
    expose:
      - 8000
    depends_on:
      - minio
      - images
    env_file:
      - .env
    environment:
      - PRIVATE_URL=http://images:8001
    volumes:
      - minio_data:/app/minio_data
      - ./web:/app/web

  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf



volumes:
  postgres_data: {}
  minio_data: {}
